version: '3.8'

services:
  # Node.js application service
  app:
    image: muzzammil759/ecomerce-app:latest
    container_name: ecommerce-app
    restart: always
    ports:
      - "3100:3000"
    env_file:
      - .env
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
